import type { CityId } from "../../src/domain/types";
import type { EventSourceDefinition } from "./types";

export const EVENT_SOURCE_REGISTRY: readonly EventSourceDefinition[] = [
  {
    id: "visit-sweden-stockholm",
    cityId: "stockholm",
    publisher: "Visit Sweden",
    canonicalUrl: "https://docs.visitsweden.com/en/api/",
    fetchUrl: "https://data.visitsweden.com/store/search",
    format: "linked_data",
    parser: "visit-sweden-linked-data",
    refreshCadenceMinutes: 24 * 60,
    trustTier: "official_api",
    termsReview: "approved",
    enabled: true,
  },
  {
    id: "ticketmaster-stockholm",
    cityId: "stockholm",
    publisher: "Ticketmaster Discovery API",
    canonicalUrl: "https://developer.ticketmaster.com/products-and-docs/apis/discovery-api/v2/",
    fetchUrl: "https://app.ticketmaster.com/discovery/v2/events.json",
    format: "ticketmaster",
    parser: "ticketmaster-discovery",
    refreshCadenceMinutes: 60,
    trustTier: "sanctioned_aggregator",
    termsReview: "approved",
    enabled: true,
  },
  {
    id: "billetto-stockholm",
    cityId: "stockholm",
    publisher: "Billetto",
    canonicalUrl: "https://api.billetto.com/reference/list-public-events",
    fetchUrl: "https://billetto.se/api/v3/public/events",
    format: "billetto",
    parser: "billetto-public-events",
    refreshCadenceMinutes: 60,
    trustTier: "sanctioned_aggregator",
    termsReview: "approved",
    enabled: true,
  },
  {
    id: "xai-san-francisco-events",
    cityId: "san-francisco",
    publisher: "xAI Web Search event collector",
    canonicalUrl: "https://docs.x.ai/docs/guides/tools/search-tools/overview",
    fetchUrl: "server-side collector",
    format: "xai_web",
    parser: "xai-web-events",
    refreshCadenceMinutes: 12,
    trustTier: "sanctioned_aggregator",
    termsReview: "approved",
    enabled: true,
  },
  {
    id: "ticketmaster-san-francisco",
    cityId: "san-francisco",
    publisher: "Ticketmaster Discovery API",
    canonicalUrl: "https://developer.ticketmaster.com/products-and-docs/apis/discovery-api/v2/",
    fetchUrl: "https://app.ticketmaster.com/discovery/v2/events.json",
    format: "ticketmaster",
    parser: "ticketmaster-discovery",
    refreshCadenceMinutes: 60,
    trustTier: "sanctioned_aggregator",
    termsReview: "approved",
    enabled: true,
  },
  ...([
    ["debaser", "Debaser", "https://debaser.se/external/events", "venue_json"],
    ["nalen", "Nalen", "https://www.nalen.com/evenemang/", "schema_org_jsonld"],
    ["sodra-teatern", "Södra Teatern", "https://sodrateatern.com/evenemang/", "schema_org_jsonld"],
    ["fasching", "Fasching", "https://www.fasching.se/kalender/", "schema_org_jsonld"],
    ["konserthuset", "Konserthuset Stockholm", "https://www.konserthuset.se/program-och-biljetter/kalender/", "event_sitemap"],
    ["kulturhuset", "Kulturhuset Stadsteatern", "https://kulturhusetstadsteatern.se/kalender", "rss_atom"],
  ] as const).map(([id, publisher, url, format]) => ({
    id: `venue-stockholm-${id}`,
    cityId: "stockholm" as const,
    publisher,
    venue: publisher,
    canonicalUrl: url,
    fetchUrl: url,
    format,
    parser: format === "venue_json" ? "venue-json-event" as const : format === "event_sitemap" ? "event-sitemap" as const : format === "rss_atom" ? "rss-atom-event" as const : "schema-org-event" as const,
    refreshCadenceMinutes: 60,
    trustTier: "first_party" as const,
    termsReview: id === "debaser" ? "approved" as const : "review_required" as const,
    enabled: id === "debaser",
    defaultVenue: id === "debaser" ? { name: "Debaser Strand", address: "Hornstulls strand 4, 117 39 Stockholm", neighborhood: "Hornstull", lat: 59.3151, lng: 18.0321 } : undefined,
  })),
  ...([
    ["sfjazz", "SFJAZZ", "https://www.sfjazz.org/calendar/", "schema_org_jsonld"],
    ["the-chapel", "The Chapel", "https://thechapelsf.com/calendar/", "schema_org_jsonld"],
    ["rickshaw-stop", "Rickshaw Stop", "https://rickshawstop.com/calendar/", "schema_org_jsonld"],
    ["bottom-of-the-hill", "Bottom of the Hill", "https://www.bottomofthehill.com/calendar.html", "schema_org_jsonld"],
    ["sfpl", "San Francisco Public Library", "https://sfpl.org/events", "ics"],
    ["the-independent", "The Independent", "https://theindependentsf.com/calendar/", "event_sitemap"],
  ] as const).map(([id, publisher, url, format]) => ({
    id: `venue-san-francisco-${id}`,
    cityId: "san-francisco" as const,
    publisher,
    venue: publisher,
    canonicalUrl: url,
    fetchUrl: url,
    format,
    parser: format === "ics" ? "ics-event" as const : format === "event_sitemap" ? "event-sitemap" as const : "schema-org-event" as const,
    refreshCadenceMinutes: 60,
    trustTier: "first_party" as const,
    termsReview: "review_required" as const,
    enabled: false,
  })),
] satisfies readonly EventSourceDefinition[];

export const eventSourcesForCity = (cityId: CityId) =>
  EVENT_SOURCE_REGISTRY.filter((source) => source.cityId === cityId);
